### ISSUE TITLE
Deprecation warning when using FFI 1.12.1

### ISSUE THREAD

**Issue by bblimke** [RubyCrypto/rbnacl#205]
FFI 1.12.1 displays the following deprecation warning:

`[DEPRECATION] Struct layout is already defined for class RbNaCl::HMAC::State. Redefinition as in /app/vendor/bundle/ruby/2.4.0/gems/rbnacl-7.1.0/lib/rbnacl/hmac/sha512256.rb:103:in `<class:State>' will be disallowed in ffi-2.0.`

**Comment by bblimke** [comment]
Thank you @orien

**Comment by bblimke** [comment]
@orien I'm afraid it didn't help. I have installed version from master:

````
[DEPRECATION] Struct layout is already defined for class RbNaCl::HMAC::State. Redefinition as in /app/vendor/bundle/ruby/2.4.0/gems/rbnacl-7.1.0/lib/rbnacl/hmac/sha512256.rb:103:in `<class:State>' will be disallowed in ffi-2.0.
[DEPRECATION] Struct layout is already defined for class RbNaCl::HMAC::State. Redefinition as in /app/vendor/bundle/ruby/2.4.0/gems/rbnacl-7.1.0/lib/rbnacl/hmac/sha512.rb:105:in `<class:State>' will be disallowed in ffi-2.0.
````

**Comment by orien** [comment]
I'm confused, the `RbNaCl::HMAC::State` class referenced in the message shouldn't exist anymore. For instance, when I attempt to reference it in a PRY REPL, it raises a `NameError`:

```
[20] pry(main)> RbNaCl::HMAC::State
NameError: uninitialized constant RbNaCl::HMAC::State
from (pry):9:in `__pry__'
```

Whereas, the three new `State` classes exist:

```
[21] pry(main)> RbNaCl::HMAC::SHA256::State
=> RbNaCl::HMAC::SHA256::State
[22] pry(main)> RbNaCl::HMAC::SHA512::State
=> RbNaCl::HMAC::SHA512::State
[23] pry(main)> RbNaCl::HMAC::SHA512256::State
=> RbNaCl::HMAC::SHA512256::State
```

I suspect you've still got version 7.1.0 loaded somehow.

**Comment by bblimke** [comment]
Thank you for confirming @orien . I must have done something wrong indeed. I have updated the gem again and I don't get the warning message anymore.

**Comment by orien** [comment]
@bblimke awesome! That’s great to hear.
