### ISSUE TITLE
Need help with sharing secret across different project

### ISSUE THREAD

**Issue by sumankula** [RubyCrypto/rbnacl#222]
I have an application 1 written in ruby which uses

```
PRIVATE_KEY = RbNaCl::Signatures::Ed25519::SigningKey.new(key)
PUBLIC_KEY = PRIVATE_KEY.verify_key

Verification is done using the following approach in ruby application

 def decode!(access_token, verify: true)
      decoded = JWT.decode(access_token, PUBLIC_KEY, verify, {algorithm: "ED25519"})[0]
      raise Errors::AuthJwt::InvalidToken unless decoded.present?

      decoded.symbolize_keys    
end

```

I need to verify the the JWT token in application 2 using different language golang i am unable to share PUBLIC_KEY for verification purpose. how can i generate a sharable public key ?

**Comment by tarcieri** [comment]
Use the `to_bytes` method: https://rubydoc.info/github/rubycrypto/rbnacl/main/RbNaCl/Signatures/Ed25519/VerifyKey#to_bytes-instance_method
